export interface HomeCateItemType {
  id: number
  label: string
  img: string
}

const homeCateList: HomeCateItemType[][] = [
  [
    {
      "id": 1,
      "label": "淘票票",
      "img": "https://gw.alicdn.com/imgextra/i2/O1CN01qrrUAN1wRjrhtfk6Q_!!6000000006305-2-tps-183-144.png_q90.jpg_.webp"
    },
    {
      "id": 2,
      "label": "飞猪旅行",
      "img": "https://gw.alicdn.com/imgextra/i3/O1CN01ULqxIg1sMvM4cBneE_!!6000000005753-2-tps-183-144.png_q90.jpg_.webp"
    },
    {
      "id": 3,
      "label": "连连消",
      "img": "https://gw.alicdn.com/imgextra/i1/O1CN01ExCBy027VMvYQPjuN_!!6000000007802-2-tps-183-144.png_q90.jpg_.webp"
    },
    {
      "id": 4,
      "label": "U先试用",
      "img": "https://gw.alicdn.com/tfs/TB1XRlKOXzqK1RjSZFCXXbbxVXa-183-144.png_q90.jpg_.webp"
    },
    {
      "id": 5,
      "label": "聚划算",
      "img": "https://gw.alicdn.com/imgextra/i1/O1CN01Lil7RM1U7JCGBNT1U_!!6000000002470-2-tps-183-144.png_q90.jpg_.webp"
    }
  ],
  [
    {
      "id": 6,
      "label": "小黑盒",
      "img": "https://gw.alicdn.com/imgextra/i4/O1CN01pFtEB01bCWtK2kxcc_!!6000000003429-2-tps-183-144.png_q90.jpg_.webp"
    },
    {
      "id": 7,
      "label": "阿里拍卖",
      "img": "https://gw.alicdn.com/imgextra/i2/O1CN01ZOR1cv1yjGFORGh1V_!!6000000006614-2-tps-183-144.png_q90.jpg_.webp"
    },
    {
      "id": 8,
      "label": "斗地主",
      "img": "https://gw.alicdn.com/imgextra/i2/O1CN01fV2JYQ1CzCaMFAxwK_!!6000000000151-2-tps-183-144.png_q90.jpg_.webp"
    },
    {
      "id": 9,
      "label": "极有家",
      "img": "https://gw.alicdn.com/imgextra/i3/O1CN012qB5SI1X5QJZt2Qsv_!!6000000002872-2-tps-183-144.png_q90.jpg_.webp"
    },
    {
      "id": 10,
      "label": "淘工厂",
      "img": "https://gw.alicdn.com/imgextra/i1/O1CN01Iqydmq1tOaWhDcEog_!!6000000005892-2-tps-183-144.png_q90.jpg_.webp"
    }
  ]
]

export default homeCateList